# Generated by Django 5.1.5 on 2025-01-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_category_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
