# Generated by Django 5.1.5 on 2025-01-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
