# Generated by Django 5.1.5 on 2025-01-22 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(
                default=1,  # Assuming a category with ID 1 exists
                on_delete=django.db.models.deletion.CASCADE, 
                to='cms.category'
            ),
            preserve_default=False,
        ),
    ]
